### ISSUE TITLE
Help getting the rigth addresses and values

### ISSUE THREAD

**Issue by rottenpants466** [teackot/msi-ec-table#1]
Hi teackot!

I saw that you replied to me here: https://github.com/BeardOverflow/msi-ec/issues/10

I was wondering if you could help me find out the correct addresses and values for my MSI laptop? 

My laptop model **MSI Summit E16 Flip A12UCT** is pretty much the same as the author of the app [MControlCenter](https://github.com/dmitry-s93/MControlCenter) **MSI Summit E16 Flip Evo A12MT** so the addresses and values are the same (i think)

In the meantime i replied to you [here](https://github.com/BeardOverflow/msi-ec/issues/10).

Thank you for your time!

**Comment by teackot** [comment]
Hi!

I think I can see your device on MControlCenter's tested devices list. Is your EC firmware version "E1592IMS.10C 08/19/2022" (first tab in the app)? It is different from authors version, so they may have some minor differences.

I want to ask some questions:

- do fan1 and fan2 speeds display correctly?
- does every mode work?
- do battery thresholds work correctly?
- and do settings from the "settings" tab work correctly?

**Comment by teackot** [comment]
Can I also ask you to install [isw](https://github.com/YoyPa/isw) and do some tests for me?

**Comment by rottenpants466** [comment]
Yes, my latest bios is **E1592IMS.10C 08/19/2022**.


- Yes, fan1 and fan2 display correctly:

![Screenshot_20230107_205421](https://user-images.githubusercontent.com/62076029/211169981-31d557e5-0908-4d69-89c3-c736bd195d26.png)

- Every mode works as intended (Checked with the `watch -n1 "cat /proc/cpuinfo | grep MHz | awk '{print $1}'"; ` command and with a browser benchmark with each mode);
- Battery thresholds also works as intended;
- Every single setting in the settings tab work as well.

Something that doesn't work (not related to MControlCenter or msi-ec driver) is the Tablet Mode (rotation sensor works fine). The issue is specifically when the screen is flipped the keyboard and touchpad doesn't disable. The author of MControlCenter also has the same issue in his laptop, [i got some help](https://gitlab.freedesktop.org/libinput/libinput/-/issues/822) from Hans de Goede but unfortunately he could not figure out the problem. After that he ask dmitry (MControlCenter) for assistance: https://github.com/dmitry-s93/MControlCenter/issues/77 

The only other thing that doesn't work as well are some keyboard keys leds. 

Other than these 2 issues everything else works ok!

**Comment by teackot** [comment]
> Can I also ask you to install isw and do some tests for me?

I need you to run this command:

```
watch -dn1 sudo isw -c
```

It will show and update an EC dump every second. You will probably have to count the column number manually and add to the row number to get the address, because it messes the header up (at least for me)

Then do these tests and see what changes (the changes are highlighted):

- press brightness down key (on my system it sets 0xed to 0xb7)
- press brightness up key (on my system it sets 0xed to 0xb8)
- plug in a device into your USB-C port (if you have any USB-C devices (charger doesn't count)) (on my system it sets 0xed to 0x79)
- press and hold Alt, Ctrl, both, and see what changes (0xd3 for me)
- plug (or unplug) AC (for me it changes 0x30)
- transform your laptop into a tablet (I suppose it should change the same byte as AC plugging)

**Comment by rottenpants466** [comment]
Yes, my latest bios is **E1592IMS.10C 08/19/2022**.


- Yes, fan1 and fan2 display correctly:

![Screenshot_20230107_205421](https://user-images.githubusercontent.com/62076029/211169981-31d557e5-0908-4d69-89c3-c736bd195d26.png)

- Every mode works as intended (Checked with the `watch -n1 "cat /proc/cpuinfo | grep MHz | awk '{print $1}'"; ` command and with a browser benchmark with each mode);
- Battery thresholds also works as intended;
- Every single setting in the settings tab works as well.

Something that doesn't work (not related to MControlCenter or msi-ec driver) is the Tablet Mode (rotation sensor works fine). The issue is specifically when the screen is flipped the keyboard and touchpad doesn't disable. The author of MControlCenter also has the same issue with his laptop, [i got some help](https://gitlab.freedesktop.org/libinput/libinput/-/issues/822) from Hans de Goede but unfortunately he could not figure out the problem. After that he ask dmitry (MControlCenter) for assistance: https://github.com/dmitry-s93/MControlCenter/issues/77 

The only other thing that doesn't work as well are some keyboard keys leds. 

Other than these 2 issues everything else works ok!


Edit: will do what you asked. I will get back to you!

**Comment by teackot** [comment]
> Edit: will do what you asked. I will get back to you!

Thanks! If Tablet Mode changes EC registers we might as well get a step closer to fixing your keyboard and touchpad not disabling

**Comment by rottenpants466** [comment]
Just a question. Does isw require the ec_sys module loaded in the kernel? MControlCenter required that and i couldn't use the app because i was using Fedora (Fedora doesn't include that module in the kernel) .

**Comment by teackot** [comment]
Yes, unfortunately it does

Maybe there is a Copr repo providing it? (Edit: I looked it up, probably not)

**Comment by rottenpants466** [comment]
I had success installing this: https://github.com/MusiKid/acpi_ec

With this i can use MControlCenter (The author also updated the app to support that acpi_ec)

**Comment by teackot** [comment]
I found an acpi_ec compatible fork: https://github.com/FaridZelli/ISW-Modern

**Comment by rottenpants466** [comment]
Nice!!

Managed to install it! Will get back to you!

**Comment by rottenpants466** [comment]
Is this area where the correct values appear? (red square)

![Screenshot_20230107_213224](https://user-images.githubusercontent.com/62076029/211171147-961906fc-1b45-47cc-82fb-0f4924590b4b.png)

**Comment by teackot** [comment]
Yes, for first 3 tests (0xed)

**Comment by teackot** [comment]
Green - AC and tablet mode

Yellow - ctrl and alt

(again, it's on my system, it may be different on yours)

![image](https://user-images.githubusercontent.com/85305327/211171437-5fa245da-a452-43b0-a531-b21000aaace9.png)

**Comment by rottenpants466** [comment]
Ok, here you go:

**Brightness down:** 0000e0 0xb7;
**Brightness up:** 0000e0 0xb8;
**Usb-C:** 0000e0 0x79 in both usb c ports (i am using a usb dock with the ac power as pass trough);
**Alt + Ctrl:** Didn't notice any change anywhere (the yellow area stays 81);
**AC Plug in:** 000030 0x07 (In both usb c ports)
**AC Plug out:** 000030 0x02
**Tablet Mode:** Didn't notice any change anywhere (the green area stays 02 while ac unplugged)

**Comment by teackot** [comment]
> Brightness down: 0000e0 0xb7;
> Brightness up: 0000e0 0xb8;
> Usb-C: 0000e0 0x79 in both usb c ports (i am using a usb dock with the ac power as pass trough);

Okay, so this may be universal for all laptops. Though I have absolutely no idea what this byte actually means.

> Alt + Ctrl: Didn't notice any change anywhere

Well, it's useless anyway

> AC Plug in: 000030 0x07 (In both usb c ports)
> AC Plug out: 000030 0x02

Good. It sets bits 0 and 2, so my code should work, but it may not be universal.

> Tablet Mode: Didn't notice any change anywhere (the green area stays 02 while ac unplugged)

:(

**Comment by teackot** [comment]
Thanks for getting the information for me! I will add a config for your and MControlCenter author's laptops in the meantime

**Comment by rottenpants466** [comment]
Sorry for asking but what byte are you referring to?

Yeah, i think maybe all the adresses and values in your ac table related to the **MSI Summit E16 Flip Evo A12MT** are the same for my model A12UCT

Thank you teackot for your time! :+1:

**Comment by teackot** [comment]
> Sorry for asking but what byte are you referring to?

I mean I have no idea why the byte you highlighted with a red square is changed specifically by brightness buttons and Type-C devices. What do these two things even have in common?

> Thank you teackot for your time! +1

:+1:

**Comment by teackot** [comment]
One more question, was you laptop in high performance mode when you did that screenshot of isw?

**Comment by rottenpants466** [comment]
In KDE system settings it was in balanced, but in MControlCenter it was in performance mode. 

For some reason after installing isw the battery thresholds stoped working in the app. Had to reset the ec

**Comment by teackot** [comment]
> In KDE system settings it was in balanced

I think what you see in KDE settings is power-profiles-daemon profiles unrelated to MSI shift modes you see in MControlCenter

> For some reason after installing isw the battery thresholds stoped working in the app

Weird, maybe it has something to do with isw systemd service

**Comment by teackot** [comment]
MControlCenter doesn't provide info about LEDs, can you tell me what LED does this command turn on:

```
sudo isw -s 0x2c 12
and then
sudo isw -s 0x2c 8
to turn it off
```

**Comment by teackot** [comment]
Or this if it doesnt work

```
sudo isw -s 0x2c 10
and then
sudo isw -s 0x2c 8
to turn it off
```

**Comment by teackot** [comment]
Or this if it doesn't work

```
sudo isw -s 0x2c 10
and then
sudo isw -s 0x2c 8
to turn it off
```

**Comment by rottenpants466** [comment]
The ones that work are: 

**0x2c 10** Turns on the led of the mute button;
**0x2c 8**  Turns off the led of the mute button;

0x2c 12 doens't seem to turn on anything

So these are all the keyboard special keys:

![IMG_20221117_175243](https://user-images.githubusercontent.com/62076029/211222442-d5cbf75e-b6c0-4853-98fa-08182be2a81c.jpg)

(Ignore the coloured numbers)

Theres a little led in the Escape, Mute Sound, Microphone and Power/Turn On laptop keys (the last one is not seen but it is on). The NUMB and CAPS LOCK keys the leds work.

**Comment by teackot** [comment]
> 0x2c 10 Turns on the led of the mute button;
> 0x2c 8 Turns off the led of the mute button;

Cool, that means **0x2b 2** will turn on mic mute led (**0x2b 0** will turn it off)

**Comment by rottenpants466** [comment]
> > 0x2c 10 Turns on the led of the mute button;
> > 0x2c 8 Turns off the led of the mute button;
> 
> Cool, that means **0x2b 2** will turn on mic mute led (**0x2b 0** will turn it off)


I think so :)

**Comment by teackot** [comment]
Done! I hope I got everything right

**Comment by teackot** [comment]
Pushed into my msi-ec repo

**Comment by rottenpants466** [comment]
:+1: 

Hope a lot of this stuff helps other people as well with their MSI laptops. There were some keys that didn't work (the ones with coloured numbers in the image above) but Hans de Goede managed to fix that: https://github.com/systemd/systemd/pull/25824 :+1:

**Comment by teackot** [comment]
Thank you very much for your help! Closing this now

**Comment by rottenpants466** [comment]
No problem :+1: 

If you need to test other stuff just ask and i will help out :)

**Comment by teackot** [comment]
Hi! It's me again

I am struggling to determing the backlight address of GS66 11UE and I noticed that some of its EC memory patterns are similar to yours.

Can I ask you to test if changing your keybooard backlight with the f8 button reflects on the [0xd3] EC address?

Here's the command (I fixed it, now it prints a normal header): `watch -d -c -n1 'sudo isw -c'`
